version: '3'
services:
  bot:
    build: .
  pg:
    image: postgres:17.2-alpine3.21
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U admin -d data"]
        interval: 10s
        timeout: 5s
        retries: 5

  volumes:
    postgres_data:
